name: flutter_tugas_1
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  fluttertoast: ^8.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/pig1.jpg
    - images/pig2.jpg
    - images/pig3.jpg
    - images/pig4.jpeg
    - images/pig5.jpg
